---
 apiVersion: v1
 kind: Service
 metadata:
   name: nodexpose
   labels:
     app: local-nginx-lb
 spec:
   type: NodePort
   ports:
     - port: 80
       nodePort: 30860
   selector:
     app: local-nginx-lb

---
 apiVersion: apps/v1beta2
 kind: Deployment
 metadata:
   name: local-nginx-lb
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: local-nginx-lb
   template:
     metadata:
       labels:
         app: local-nginx-lb
     spec:
       containers:
         - name: nginx
           image: nginx:kibana
           ports:
             - containerPort: 80
           volumeMounts:
             - name: nginx-logs
               mountPath: /var/logs
           imagePullPolicy: Never
       volumes:
         - name: nginx-logs
           hostPath:



