---
 apiVersion: v1
 kind: Service
 metadata:
   name: nginx-proxy
   labels:
     app: local-nginx-lb
 spec:
   type: NodePort
   ports:
     - port: 80
       nodePort: 30860
   selector:
     app: local-nginx-lb

---
 apiVersion: apps/v1beta2
 kind: Deployment
 metadata:
   name: local-nginx-lb
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: local-nginx-lb
   template:
     metadata:
       labels:
         app: local-nginx-lb
     spec:
       containers:
         - name: nginx
           image: ashwanikp42/nginx:my-elk
           ports:
             - containerPort: 80
           volumeMounts:
             - name: nginx-logs
               mountPath: /var/logs
           command: ['bash', '-c', '/etc/init.d/nginx start && htpasswd -b -c /etc/nginx/htpasswd.users kibanaadmin ankur && tail -f /dev/null']
           imagePullPolicy: IfNotPresent
       volumes:
         - name: nginx-logs
           hostPath:
